/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function writeToJson(
  p: string,
  docker: boolean | undefined | null,
  data: unknown,
): string;
export function readJson(
  p: string,
  docker?: boolean | undefined | null,
): unknown;
