version: "3"
services:
  bot:
    container_name: bot
    image: proudcobolwriter/n-word-monitor
    build: .
    environment:
      - TOKEN=$TOKEN
      - CLIENT_ID=$CLIENT_ID
      - GUILD_ID=$GUILD_ID
      - EXPLICIT_WORDS=$EXPLICIT_WORDS
      - PIXABAY_API_KEY=$PIXABAY_API_KEY
      - HOST_URL=$HOST_URL
      - HOST_PORT=$HOST_PORT
      - NODE_ENV=production
    ports:
      - "${HOST_PORT}:3000"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/n-word-monitor/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    volumes:
      - db-data:/usr/local/apps/n-word-monitor/
    restart: unless-stopped

volumes:
  db-data:
